*** Settings ***
Library     RequestsLibrary
Documentation    Afficher la liste des environnements

*** Variables ***
${base_url}     http://sige-referentiel-service.dev.defisetstrategies.dev/api
${endpoint}     /v1/environnements?page=0&size=10
${bearerToken}=    Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDUENBalAxM3lKbGdoSXJZYkp0QnBQc1NZeVBNMHRSaGpNdHJVUkh1TXJ3In0.eyJleHAiOjE2OTk4ODI3MjksImlhdCI6MTY5OTg4MjQyOSwianRpIjoiYTdhY2ViYTktZTM1NC00MDBkLThhNzUtODc5ZjFlMDAxYmE0IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5kZXYuZGVmaXNldHN0cmF0ZWdpZXMuZGV2L3JlYWxtcy9zaWdlbWVuYSIsImF1ZCI6WyJhY2NvdW50IiwiYXhlbG9yLWRldi10ZXN0Il0sInN1YiI6IjJhMDAyZmRiLTkzMzEtNDc2Zi05YzFjLWE2MDQ2NDBiNmIyMyIsInR5cCI6IkJlYXJlciIsImF6cCI6InBvcnRhaWwtYmFja29mZmljZS1kZXYiLCJzZXNzaW9uX3N0YXRlIjoiZTkwYjA4ODEtZmIwZi00YmJiLWEyZmQtNWI4YTEzZDE0MjE3IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtc2lnZW1lbmEiLCJ1bWFfYXV0aG9yaXphdGlvbiIsInJvbGUucmgiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX0sImF4ZWxvci1kZXYtdGVzdCI6eyJyb2xlcyI6WyJBZG1pbiIsInJvbGUucmgiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJlOTBiMDg4MS1mYjBmLTRiYmItYTJmZC01YjhhMTNkMTQyMTciLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJFdGllbiBHaGlzbGFpbiBHaGlzbGFpbiIsInByZWZlcnJlZF91c2VybmFtZSI6IjAxODA2NnciLCJnaXZlbl9uYW1lIjoiRXRpZW4gR2hpc2xhaW4iLCJmYW1pbHlfbmFtZSI6IkdoaXNsYWluIiwiZW1haWwiOiJnaGlzbGFpbmV0aWVuQGdtYWlsLmNvbSJ9.jtUZw00UDNRZ69arlxLLz5WdzqHV3I7t31w4UQkMJBD0pO-OZSRQTqHofEHw_3xgIZLaMYVQ0_RV62eEFWk4SNouATwQyZPYkVqajMYUMmBB5ItXGPvtx6yVJ0PRMREs5HElLNIfsjGJMaAkHW8KSSfBtmKQ9gOlDHHl5oozkVaQqR5ofcyVGmOiXTFPBIWBBoQx9Aj3VHquREWx_GLUX-ESS-ZL-9hF5UaavFW3MaXcvfntOuWkk-Apxiyq1KAfOmP8sA9wBtSNQ8NCX-nCTlN0FWQVI5QZmpx8qBV8EHrzvtfCEVIZ4_VOYr6q7-S0TyFOOLBNwS6CAipkgSgivQ

*** Test Cases ***
Parametres
    create session    ma_session    ${base_url}
    ${header}=    Create Dictionary    Authorization=${bearerToken}    Content-Type=application/json
    ${response}=    get request    ma_session   ${endpoint}     headers=${header}

    log to console    ${response.status_code}
    log to console    ${response.content}
    log to console    ${response.headers}


